language: java
jdk: openjdk8
script: 
  - cd ResstApp/
  - mvn clean verify --batch-mode -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

after_success:
  - mvn clean test jacoco:report coveralls:report

services:
  - mysql

before_script:
  - wget https://repo.mysql.com//mysql-apt-config_0.8.10-1_all.deb
  - sudo dpkg -i mysql-apt-config_0.8.10-1_all.deb
  - sudo apt-get clean
  - sudo apt-get update
  - sudo apt-get install -q -y --allow-unauthenticated -o Dpkg::Options::=--force-confnew mysql-server
  - sudo systemctl restart mysql
  - sudo mysql_upgrade
  - mysql --version 
  - mysql -u root -e 'CREATE DATABASE tacs;'
  - mysql -u root -e "CREATE USER 'tacs'@'localhost' IDENTIFIED BY 'tacs';"
  - mysql -u root -e "GRANT ALL ON tacs.* TO 'tacs'@'localhost';"
